CREATE or replace PIPE SPOTIFY_DATA.SPOTIFY.PIPEALBUM
AUTO_INGEST = TRUE
as
copy into SPOTIFY_DATA.SPOTIFY.TABLEALBUM
from @spotify_data

CREATE or replace PIPE SPOTIFY_DATA.SPOTIFY.PIPESONG
AUTO_INGEST = TRUE
as
copy into SPOTIFY_DATA.SPOTIFY.TBLSONG
from @spotify_data

CREATE or replace PIPE SPOTIFY_DATA.SPOTIFY.PIPEARTIST
AUTO_INGEST = TRUE
as
copy into SPOTIFY_DATA.SPOTIFY.TBLARTIST
from @spotify_data

desc pipe SPOTIFY_DATA.SPOTIFY.PIPESONG;